swagger: "2.0"
info:
  version: "v1"
  title: 弹性公网ip
  description: 弹性公网ip相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/elasticIps/":
    get:
      operationId: describeElasticIps
      summary: "查询弹性ip列表"
      description: "查询弹性ip列表"
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页"
          
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "分页大小，默认为20，取值范围：[10,100]"
          
        - name: filters
          in: query
          type: array
          items:
            #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            elasticIpIds - elasticip id数组条件，支持多个
            elasticIpAddress - eip的IP地址，支持单个
            chargeStatus	- eip的费用支付状态,normal(正常状态) or overdue(预付费已到期) or arrear(欠费状态)，支持单个

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                description: "返回结果"
                type: object
                properties:
                  elasticIps:
                    description: "elasticIp资源信息列表"
                    type: array
                    items:
                      #$ref: "/jcloud-open-api/vpc/model/ElasticIp.yaml#/definitions/elasticIp"
                      $ref: "../model/ElasticIp.yaml#/definitions/elasticIp"
                  totalCount:
                    description: "总数量"
                    type: integer
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "invalid parameter"
        401:
          description: "Authentication failed"
    
    post:
      summary: "创建一个或者多个弹性Ip"
      description: "创建一个或者多个弹性Ip"
      operationId: createElasticIps
      parameters:
        - name: createElasticIpSpec
          in: body
          required: true
          description: "申请创建弹性ip请求参数"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/CreateElasticIpSpec.yaml#/definitions/createElasticIpSpec"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              result:
                description: "返回结果"
                properties:
                  elasticIpIds:
                    description: "弹性IP ID列表"
                    type: array
                    items:
                      type: string
                      description: 弹性IP ID
                  requestId:
                    description: "请求ID"
                    type: string
        400:
          description: "Invalid param 'xxx'"
        401:
          description: "Unauthenticated user pin 'xxx'"
        500:
          description: "Unknown server error"
        503:
          description: "Service unavailable"


  "/elasticIps/{elasticIpId}":
      #describe ElasticIp
      get:
        summary: "ElasticIp资源信息详情"
        description: "ElasticIp资源信息详情"
        operationId: describeElasticIp
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "返回结果"
                  properties:
                    elasticIp:
                      description: "elasticIp资源信息"
                      $ref: "../model/ElasticIp.yaml#/definitions/elasticIp"
                requestId:
                  description: "请求ID"
                  type: string
          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"
      
      #delete ElasticIp
      delete:
        summary: "删除弹性Ip"
        description: "删除弹性Ip"
        operationId: deleteElasticIp
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "请求ID"
                  type: string
          400:
            description: "Invalid param 'xxx'"
          404:
            description: "elasticIp 'xxx' not found"
          500:
            description: "Unknown server error"
          503:
            description: "Service unavailable"

      patch:
        summary: "修改弹性IP"
        description: "修改弹性IP"
        x-jdcloud-internal: true
        operationId: modifyElasticIp
        parameters:
          - name: modifyElasticIpSpec
            in: body
            required: true
            description: "修改弹性IP"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifyElasticIpSpec.yaml#/definitions/modifyElasticIpSpec"

        responses:
         200:
            description: Successful operation
            schema:
              type: object
              properties:
                 requestId:
                    description: "请求ID"
                    type: string
         400:
            description: "Invalid param 'xxx'"
         404:
            description: Resource not found
          
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  elasticIpId:
    name: elasticIpId
    in: path
    required: true
    type: string
    description: ElasticIp ID
        

    
