swagger: "2.0"
definitions:
  webRuleSpec:
    type: object
    x-jdcloud-module: ipanti
    properties:
      domain:
        type: string
        description: 子域名
      protocol:
        type: string
        description: 协议：HTTP、HTTPS、HTTP_HTTPS
      port:
        type: string
        description: HTTP协议的端口号，如80,81，多个端口号使用逗号分隔
      httpsPort:
        type: string
        description: HTTPS协议的端口号，如443,8443，多个端口号使用逗号分隔
      originType:
        type: string
        description: 回源类型：A或者CNAME
      originAddr:
        type: array
        items:
          $ref: "../model/OriginAddrItem.yaml#/definitions/OriginAddrItem"
      onlineAddr:
        type: array
        items:
          type: string
      originDomain:
        type: string
        description: 回源域名,originType为CNAME时需要指定该字段
      httpsCertContent:
        type: string
        description: 证书内容
      httpsRsaKey:
        type: string
        description: 证书私钥
      algorithm:
        type: string
        description: 转发规则：wrr->带权重的轮询 rr->不带权重的轮询
      forceJump:
        type: integer
        description: 是否开启https强制跳转，当protocol为HTTP_HTTPS时可以配置该属性 0->不强跳 1->开启强跳
      customPortStatus:
        type: integer
        description: 是否为自定义端口号，0->默认 1->自定义
      httpOrigin:
        type: integer
        description: 是否开启http回源，0->不开启 1->开启，当勾选HTTPS时可以配置该属性