swagger: "2.0"                                  # 基于Swagger 2.0版本实现
info:
  version: "v1"                                 # OpenApi版本号
  title: 数据计算服务API
  description: 数据计算服务相关API
host: "xdata.jdcloud-api.com"                   # 业务线名称作为二级域名
x-jdcloud-version: "v1"
x-jdcloud-revision: 1.0.0  #需要和ChangeLog保持一致
