swagger: "2.0"
info:
  version: "v1"
  title: 镜像
  description: 关于主机镜像操作的相关接口

basePath: /regions/{regionId}

paths:
  "/images/{imageId}":
    ###################### 镜像详情接口 ######################
    get:
      description: |
        查询镜像详情。
      operationId: describeImage
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  image:
                    description: 镜像详情
                    $ref: "../model/Image.yaml#/definitions/image"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 删除镜像接口 ######################
    delete:
      description: |
        删除一个私有镜像，只允许操作您的个人私有镜像。<br>
        若镜像已共享给其他用户，需先取消共享才可删除。
      operationId: deleteImage
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images":
    ###################### 镜像列表接口 ######################
    get:
      description: |
        查询镜像信息列表。<br>
        通过此接口可以查询到京东云官方镜像、第三方镜像、私有镜像、或其他用户共享给您的镜像。<br>
        此接口支持分页查询，默认每页20条。
      operationId: describeImages
      parameters:
        - name: imageSource
          in: query
          type: string
          description: "镜像来源，如果没有指定ids参数，此参数必传；取值范围：public、shared、thirdparty、private"
        - name: platform
          in: query
          type: string
          description: "操作系统平台，取值范围：Windows Server、CentOS、Ubuntu"
        - name: ids
          in: query
          type: array
          items:
            type: string
          description: "镜像ID列表，如果指定了此参数，其它参数可为空"
        - name: rootDeviceType
          in: query
          type: string
          description: "镜像支持的系统盘类型，[localDisk,cloudDisk]"
        - name: status
          in: query
          type: string
          description: <a href="http://docs.jdcloud.com/virtual-machines/api/image_status">参考镜像状态</a>
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "页码；默认为1"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "分页大小；默认为20；取值范围[10, 100]"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  images:
                    type: array
                    description: 镜像详情
                    items:
                      $ref: "../model/Image.yaml#/definitions/image"
                  totalCount:
                    type: integer
                    description: 总数量
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}/constraints":
    ###################### 查询镜像限制接口 ######################
    get:
      description: |
        查询镜像的实例规格限制。<br>
        通过此接口可以查看镜像不支持的实例规格。只有官方镜像、第三方镜像有实例规格的限制，个人的私有镜像没有此限制。
      operationId: describeImageConstraints
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  imageConstraints:
                    type: object
                    description: 镜像限制
                    $ref: "../model/ImageConstraint.yaml#/definitions/imageConstraint"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/imageConstraints":
    ###################### 批量查询镜像限制 ######################
    get:
      description: |
        批量查询镜像的实例规格限制。<br>
        通过此接口可以查看镜像不支持的实例规格。只有官方镜像、第三方镜像有实例规格的限制，个人的私有镜像没有此限制。
      operationId: describeImageConstraintsBatch
      parameters:
        - name: ids
          in: query
          type: array
          items:
            type: string
          description: "镜像ID列表"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  imageConstraints:
                    type: array
                    items:
                      $ref: "../model/ImageConstraint.yaml#/definitions/imageConstraint"
                    description: 镜像限制
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:share":
    ###################### 共享镜像 ######################
    post:
      description: |
        共享镜像，只允许操作您的个人私有镜像，单个镜像最多可共享给20个京东云帐户。<br>
        整机镜像目前不支持共享。
      operationId: shareImage
      parameters:
        - name: pins
          in: query
          type: array
          items:
            type: string
          description: 需要共享的帐户
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:unshare":
    ###################### 取消共享镜像 ######################
    post:
      description: |
        取消共享镜像，只允许操作您的个人私有镜像。
      operationId: unShareImage
      parameters:
        - name: pins
          in: query
          type: array
          items:
            type: string
          description: 需要取消的帐户
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}/members":
    ###################### 查询镜像共享帐户列表 ######################
    get:
      description: |
        查询镜像共享帐户列表，只允许操作您的个人私有镜像。
      operationId: describeImageMembers
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pins:
                    type: array
                    description: 用户Pin列表
                    items:
                      type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:convertImage":
    ###################### 镜像转换 ######################
    post:
      description: |
        内部接口。<br>
        镜像转换，只支持镜像从localDisk转换到cloudDisk类型，只允许操作您的个人私有镜像。
      operationId: convertImage
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  imageId:
                    type: string
                    description: 转换后新镜像的ID
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images:copyImages":
    ###################### 镜像跨区复制 ######################
    post:
      description: |
        镜像跨区复制，将私有镜像复制到其它地域下，只允许操作您的个人私有镜像。<br>
        只支持rootDeviceType为cloudDisk的云硬盘系统盘镜像操作。
      operationId: copyImages
      parameters:
        - name: sourceImageIds
          in: query
          type: array
          items:
            type: string
          required: true
          description: 源镜像ID
        - name: destinationRegion
          in: query
          type: string
          required: true
          description: 目标区域
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  copyImages:
                    type: array
                    description: 源镜像与目标镜像映射关系
                    items:
                      $ref: "../model/CopyImage.yaml#/definitions/copyImage"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:modifyImageAttribute":
    ###################### 修改镜像信息 ######################
    post:
      description: |
        修改镜像信息，包括名称、描述；只允许操作您的个人私有镜像。
      operationId: modifyImageAttribute
      parameters:
        - name: name
          in: query
          type: string
          description: 名称，<a href="http://docs.jdcloud.com/virtual-machines/api/general_parameters">参考公共参数规范</a>。
        - name: description
          in: query
          type: string
          description: 描述，<a href="http://docs.jdcloud.com/virtual-machines/api/general_parameters">参考公共参数规范</a>。
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID
  imageId:
    name: imageId
    in: path
    required: true
    type: string
    description: 镜像ID
