swagger: "2.0"
info:
  version: "v1"
  title: 实例规格
  description: 与实例规格操作相关的接口

basePath: /regions/{regionId}

paths:
  "/instanceTypes":
    ###################### 规格列表接口 ######################
    get:
      description: |
        查询实例规格信息列表
      operationId: describeInstanceTypes
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            instanceTypes - 实例规格，精确匹配，支持多个
            az - 可用区，精确匹配，支持多个
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  instanceTypes:
                    description: 通用的实例规格
                    type: array
                    items:
                      $ref: "../model/InstanceType.yaml#/definitions/instanceType"
                  specificInstanceTypes:
                    description: 用户特有的实例规格；需要工单申请
                    type: array
                    items:
                      $ref: "../model/InstanceType.yaml#/definitions/instanceType"
                  totalCount:
                    type: integer
                    description: 总数量
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID
