/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * apiName0
 * petstore api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package net.jdcloud.PetStore.model;

import com.jdcloud.sdk.service.JdcloudResponse;
import java.util.Objects;
import java.util.Arrays;
import java.math.BigDecimal;
import java.io.Serializable;
import javax.xml.bind.annotation.*;

/**
 * ApiName0Response
 */
@XmlRootElement(name = "ApiName0Response")
@XmlAccessorType(XmlAccessType.FIELD)

public class ApiName0Response extends JdcloudResponse implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlElement(name = "price")
    private BigDecimal price = null;

    @XmlElement(name = "id")
    private Integer id = null;

    @XmlElement(name = "type")
    private String type = null;

    public ApiName0Response price(BigDecimal price) {
        this.price = price;
        return this;
    }

    /**
     * petprice
     * @return price
    **/

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public ApiName0Response id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * petId
     * @return id
    **/

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ApiName0Response type(String type) {
        this.type = type;
        return this;
    }

    /**
     * pettype
     * @return type
    **/

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


}

