/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * apiName1
 * petstore api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package net.jdcloud.PetStore.model;

import com.jdcloud.sdk.service.JdcloudResponse;
import java.util.Objects;
import java.util.Arrays;
import net.jdcloud.PetStore.model.ApiName1Pet;
import java.io.Serializable;
import javax.xml.bind.annotation.*;

/**
 * ApiName1Response
 */
@XmlRootElement(name = "ApiName1Response")
@XmlAccessorType(XmlAccessType.FIELD)

public class ApiName1Response extends JdcloudResponse implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlElement(name = "message")
    private String message = null;

    @XmlElement(name = "pet")
    private ApiName1Pet pet = null;

    public ApiName1Response message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     * @return message
    **/

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public ApiName1Response pet(ApiName1Pet pet) {
        this.pet = pet;
        return this;
    }

    /**
     * Get pet
     * @return pet
    **/

    public ApiName1Pet getPet() {
        return pet;
    }

    public void setPet(ApiName1Pet pet) {
        this.pet = pet;
    }


}

