/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * apiName0
 * petstore api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package net.jdcloud.PetStore.model;

import com.jdcloud.sdk.service.JdcloudRequest;
import com.jdcloud.sdk.annotation.*;
import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;
import javax.xml.bind.annotation.*;

/**
 * ApiName0Request
 */
@XmlRootElement(name = "ApiName0Request")
@XmlAccessorType(XmlAccessType.FIELD)

public class ApiName0Request extends JdcloudRequest implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlElement(name = "petId")
    @PathParameter
    private String petId = null;

    public ApiName0Request petId(String petId) {
        this.petId = petId;
        return this;
    }

    /**
     * ID of pet to return
     * @return petId
    **/

    public String getPetId() {
        return petId;
    }

    public void setPetId(String petId) {
        this.petId = petId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApiName0Request apiName0Request = (ApiName0Request) o;
        return Objects.equals(this.petId, apiName0Request.petId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(petId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApiName0Request {\n");
        
        sb.append("    petId: ").append(toIndentedString(petId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
          return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

