/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * apiName1
 * petstore api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package net.jdcloud.PetStore.model;

import com.jdcloud.sdk.annotation.*;
import java.util.Objects;
import java.util.Arrays;
import java.math.BigDecimal;
import java.io.Serializable;
import javax.xml.bind.annotation.*;

/**
 * ReqBody
 */
@XmlRootElement(name = "ReqBody")
@XmlAccessorType(XmlAccessType.FIELD)

public class ReqBody implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlElement(name = "price")
    private BigDecimal price = null;

    @XmlElement(name = "id")
    private Integer id = null;

    @XmlElement(name = "type")
    private String type = null;

    public ReqBody price(BigDecimal price) {
        this.price = price;
        return this;
    }

    /**
     * petprice
     * @return price
    **/

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public ReqBody id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * petId
     * @return id
    **/

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ReqBody type(String type) {
        this.type = type;
        return this;
    }

    /**
     * pettype
     * @return type
    **/

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReqBody reqBody = (ReqBody) o;
        return Objects.equals(this.price, reqBody.price) &&
        Objects.equals(this.id, reqBody.id) &&
        Objects.equals(this.type, reqBody.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(price, id, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReqBody {\n");
        
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
          return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

