swagger: "2.0"
definitions:
  copyImage:
    x-jdcloud-module: vm
    properties:
      destinationImageId:
        type: string
        description: 复制后的目标镜像ID
      sourceImageId:
        type: string
        description: 源镜像ID