swagger: "2.0"
definitions:
  instanceTemplateNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    required:
      - networkInterface
    properties:
      deviceIndex:
        type: integer
        description: 设备Index；主网卡的index必须为1；当前仅支持主网卡
      autoDelete:
        type: boolean
        description: 指明删除实例时是否删除网卡，默认true；当前只能是true
      networkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceSpec.yaml#/definitions/instanceTemplateNetworkInterfaceSpec"
        description: 网卡接口规范；此字段当前必填