swagger: "2.0"
definitions:
  instanceType:
    x-jdcloud-module: vm
    properties:
      family:
        type: string
        description: 实例规格类型
      instanceType:
        type: string
        description: 实例规格，比如g.b1.2xlarge
      cpu:
        type: integer
        description: cpu个数
      memoryMB:
        type: integer
        description: 内存大小
      nicLimit:
        type: integer
        description: 支持弹性网卡的数量
      desc:
        type: string
        description: 描述
      state:
        type: array
        items:
          $ref: "./InstanceTypeState.yaml#/definitions/instanceTypeState"
        description: 规格状态