swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: 网卡设备Index，主网卡只能是1
      networkInterface:
        $ref: "../../vpc/model/NetworkInterfaceSpec.yaml#/definitions/networkInterfaceSpec"
        description: 网卡接口规范
