swagger: "2.0"
definitions:
  instanceTemplateSpec:
    x-jdcloud-module: vm
    required:
      - instanceType
      - imageId
      - primaryNetworkInterface
      - systemDisk
    properties:
      instanceType:
        type: string
        description: 实例规格，可查询<a href="https://www.jdcloud.com/help/detail/2901/isCatalog/1">DescribeInstanceTypes</a>接口获得指定地域或可用区的规格信息。
      imageId:
        type: string
        description: 镜像ID，可查询<a href="https://www.jdcloud.com/help/detail/2874/isCatalog/1">DescribeImages</a>接口获得指定地域的镜像信息。
      password:
        type: string
        description: 密码，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      keyNames:
        type: array
        items:
          type: string
        description: 密钥对名称；当前只支持一个
      elasticIp:
        $ref: "./InstanceTemplateElasticIpSpec.yaml#/definitions/instanceTemplateElasticIpSpec"
        description: 主网卡主IP关联的弹性IP规格
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: 主网卡配置信息
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: 系统盘配置信息
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: 数据盘配置信息